tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask_args appdir: "~/Applications"

brew "bat"
brew "cmake"
brew "direnv"
brew "exa"
brew "fd"
brew "git-delta"
brew "git-lfs"
brew "jq"
brew "llvm"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "nvm"
brew "ripgrep"
brew "rust-analyzer"
brew "the_silver_searcher"
brew "zsh"
brew "antigen"
brew "python"
brew "nushell"

cask "font-iosevka-nerd-font"
